// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/api/joke.ts";
import * as $3 from "./routes/api/webcam.ts";
import * as $4 from "./routes/camera/[id].tsx";
import * as $5 from "./routes/camera/index.tsx";
import * as $6 from "./routes/details.tsx";
import * as $7 from "./routes/index.tsx";
import * as $$0 from "./islands/Canvas.tsx";
import * as $$1 from "./islands/Counter.tsx";
import * as $$2 from "./islands/OverlayImage.tsx";
import * as $$3 from "./islands/RefreshingImage.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/api/joke.ts": $2,
    "./routes/api/webcam.ts": $3,
    "./routes/camera/[id].tsx": $4,
    "./routes/camera/index.tsx": $5,
    "./routes/details.tsx": $6,
    "./routes/index.tsx": $7,
  },
  islands: {
    "./islands/Canvas.tsx": $$0,
    "./islands/Counter.tsx": $$1,
    "./islands/OverlayImage.tsx": $$2,
    "./islands/RefreshingImage.tsx": $$3,
  },
  baseUrl: import.meta.url,
};

export default manifest;
